const data = [
    {
      id: 1,
      label: "Senior .Net developer",
      images: "assets/images/icons/dotnet.png",
      description:
        "Deal candidates must be fully competent with key technical skills including:",
      skills: [
        { skill: "SP.NET 4.0 (C#)" },
        { skill: " JQuery/JavaScript " },
        { skill: "MVC 3.0+ " },
        {
          skill:
            "SQL Server 2008/2012 (Transact SQL, Stored Procedures, Triggers)",
        },
        { skill: "AJAX Techniques" },
        { skill: "Entity Frameworks and LINQ" },
        { skill: "HTML5, Razor View engine, CSS and jQuery/JavaScript" },
      ],
      minExperience: "",
      requirment: [],
      vacancy: "5",
    },
  
    {
      id: 2,
      label: "Full Stack Developer",
      images: "assets/images/icons/fullstack.png",
      description:
        "We Are Searching For Another Talented Full Stack Web Developer To Join Our Team! The Candidate Will Be Proficient With Both Frontend And Backend Development Technologies, Possessing In-Depth Experience In Both.",
      skills: [
        { skill: "PHP : PHP 5 , PHP 7 And Upper Version" },
        {
          skill:
            " PHP Framework : LARAVEL And CI, Must Have Working Experience In Both",
        },
        {
          skill:
            " JS Frontend Framework : Angular, React And Vue Js, Must Have Working Experience In Any Two Framework",
        },
        { skill: "Backend: Minimun 1 Yrs Experience In Node.Js" },
        { skill: " DB : MySql, MongoDB" },
        {
          skill:
            "Server Side: Knowledge Of AWS, S3, Docker, Azure Is An Advantage",
        },
        { skill: "Knowledge Of Python And Django Is An Advantage" },
        { skill: "Strong Communication Skills" },
      ],
      minExperience: "3 Yrs onwards",
      requirment: [
        {
          req: "Education: (UG - Any Graduate - Any Specialization) And (PG - Any PG Course - Any Specialization, Post Graduation Not Required)",
        },
        { req: "Industry: Web, Software Development, Design, Mobile App" },
        { req: "Functional Area: Web, Software Development" },
        { req: "Role Category: Senior Drupal Developer" },
        { req: "Minimum Experience : 2 Yrs Onwards" },
      ],
      vacancy: "5",
    },

    {id: 3,
    label: "Senior PHP Developer",
    images: "assets/images/icons/php.png",
    description:"Ideal Candidates Must Be Fully Competent With Key Technical Skills Including:",
    skills: [
      { skill: "*PHP 5, MYSQL 5" },
      { skill: "*Opensource (Any One Of Them) : WordPress/Joomla/Oscommerc/Smarty /Drupal/Magento" },
      { skill: " *Framework (Any One Of Them) : Codeigniter/Zend/YII/Laravel/CakePHP" },
      {
        skill:
          "*Scripting : Javascript (Ajax) And Web Concepts Knowledge, *OOPS, XML, *Facebook API/Yahoo API/Twitter API/Google MapAPI",
      },
      { skill: "*Knowledge Of Angular JS, Node JS, Raphael Js, Svg, HTML5 Would Be A Plus (Not Mandatory). Education: (UG - Any Graduate - Any Specialization) And (PG - Any PG Course - AnySpecialization, Post Graduation Not Required)" },
      { skill: "Industry: Web, Software Development, Design, Mobile App" },
      { skill: "Functional Area: Web, Software Development" },
      { skill: "Role Category: Senior PHP Developer" },
    ],
    minExperience: "",
    requirment: [],
    vacancy: "5",
    },
    {id: 4,
    label: "Junior PHP Developer",
    images: "assets/images/icons/php.png",
    description:"Ideal Candidates Must Be Fully Competent With Key Technical Skills Including:",
    skills: [
      { skill: "*PHP 5, MYSQL 5" },
      { skill: "*Opensource (Any One Of Them) : WordPress/Joomla/Oscommerc/Smarty /Drupal/Magento" },
      { skill: "*Framework (Any One Of Them) : Codeigniter/Zend/YII/Laravel/CakePHP (Will Be An Added Advantage)" },
      {
        skill:
          "*Scripting : Javascript (Ajax) And Web Concepts Knowledge, *OOPS, XML, *FacebookAPI/Yahoo API/Twitter API/Google Map API",
      },
      { skill: "Education: (UG - Any Graduate - Any Specialization) And (PG - Any PG Course - Any Specialization, Post Graduation Not Required)" },
      { skill: "Industry: Web, Software Development, Design, Mobile App" },
      { skill: "Functional Area: Web, Software Development" },
      { skill: "Role Category: Senior PHP Developer" },
      { skill: "Minimum Experience : 1 Yr" },
    ],
    minExperience: "",
    requirment:  [],
    vacancy: "3",
    },
    {id: 5,
      label: "Drupal Developer",
      images: "assets/images/icons/drupal.png",
      description:"Ideal Candidates Must Be Fully Competent With Key Technical Skills Including:",
      skills: [
        { skill: "Experience Buildingresponsive Websites Using Drupal CMS, Php, HTML/HTML5, CSS/CSS3, And JavaScript/JQuery Experience Developing Web Solutions In Drupal And PHP Implementations" },
        { skill: "Ability To Architectenterprise Drupal Solutions Including Data, Display, And Information Architecture" },
        { skill: "Advanced Site-Building Experience Including Deep Familiarity With Drupal Modules Such AsCTools, Views, And Panels" },
        {
          skill:
            "Experience Creating Custom Drupal Modules",
        },
        
      ],
      minExperience: "Candicate Must Have Min 2 Yrs Working Experience In Drupal 8.",
      requirment: [
        {
          req: "Education: (UG - Any Graduate - Any Specialization) And (PG - Any PG Course - Any Specialization, Post Graduation Not Required)",
        },
        { req: "Industry: Web, Software Development, Design, Mobile App" },
        { req: "Functional Area: Web, Software Development" },
        { req: "Role Category: Senior Drupal Developer" },
        { req: "Minimum Experience : 2 Yrs Onwards" },
      ],
      vacancy: "5",
    },
    {id: 6,
      label: "Node JS Developer",
      images: "assets/images/icons/node.png",
      description:"Deal Candidates Must Be Fully Competent With Key Technical Skills Including:",
      skills: [
        { skill: "Strong Proficiency With JavaScript And Expertise In Node.Js" },
        { skill: "Should Have Relevant Experience InMongoDB, Express JS, StrongLoop, Etc" },
        { skill: "Strong Knowledge Of Back-End Programming Languages Such As JavaScript, TypeScript, And Node.Js Framework" },
        {
          skill:
            "Understanding The Nature Ofasynchronous Programming",
        },
        { skill: "Basic Understanding Of Templating Languages (EJS, Jade, Etc)" },
        { skill: "Basic Understanding Of Pre-Processors (Sass, Babel, Etc)" },
        { skill: "Basic Understanding Of Front-End Technologies (HTML5, CSS3, ES5+)" },
        { skill: "Database Experience In MySQL, PostgreSQL, SQLite Added Extra Advantages" },
        { skill: "Knowlegde Of Angular Js / VueJs/React Js Added Extra Advantages" },
        { skill: "Strong Knowledge In Writing Unit Testing And E2e Testing" },
       
      ],
      minExperience: "",
      requirment: [
        {
          req: "Education: (UG - Any Graduate - Any Specialization) And (PG - Any PG Course - Any Specialization, Post Graduation Not Required)",
        },
        { req: "Industry: Web, Software Development, Design, Mobile App" },
        { req: "Functional Area: Web, Software Development" },
        { req: "Role Category: Senior Drupal Developer" },
        { req: "Minimum Experience : 2 Yrs Onwards" },
      ],
      vacancy: "2",
    },
    {id: 7,
      label: "Senior Angular Developer",
      images: "assets/images/icons/angular.png",
      description:"Deal Candidates Must Be Fully Competent With Key Technical Skills Including:",
      skills: [
        { skill: "Experience Building Enterprise Applications Angular, JavaScript And HTML5" },
        { skill: "Strong Proficiency In Angular 6 And Other Versions(7/8/9), JavaScript, Including DOM Manipulation And The JavaScript Object Model" },
        { skill: "Experience With Popular Angular Workflows" },
        {
          skill:
            "Familiarity With RESTful APIs",
        },
        { skill: "*Knowledge Of Angular JS, Node JS, Raphael Js, Svg, HTML5 Would Be A Plus (Not Mandatory). Education: (UG - Any Graduate - Any Specialization) And (PG - Any PG Course - AnySpecialization, Post Graduation Not Required)" },
        { skill: "Industry: Web, Software Development, Design, Mobile App" },
        { skill: "Functional Area: Web, Software Development" },
        { skill: "Role Category: Senior PHP Developer" },
      ],
      minExperience: "",
      requirment: [
        {
          req: "Education: (UG - Any Graduate - Any Specialization) And (PG - Any PG Course - Any Specialization, Post Graduation Not Required)",
        },
        { req: "Industry: Web, Software Development, Design, Mobile App" },
        { req: "Functional Area: Web, Software Development" },
        { req: "Role Category: Senior Drupal Developer" },
        { req: "Minimum Experience : 2 Yrs Onwards" },
      ],
      vacancy: "2",
    },
    {id: 8,
      label: "Senior Moodle Developer",
      images: "assets/images/icons/module.png",
      description:"Deal Candidates Must Be Fully Competent With Key Technical Skills Including:",
      skills: [
        { skill: "Moodle V3.2 Or Higher Development Experience" },
        { skill: "Experience In Moodle Integration With Third Party Applications Using LTI Or LTI Advantage" },
        { skill: "Experience With Moodle Module / Block Development," },
        {
          skill:
            "Should Be Able To Develop Moodle Plugin",
        },
        { skill: "Understand The Moodle Core And Modify It If Needed" },
        { skill: "Reasonable Knowledge Of Moodle Theme Customisation" },
        { skill: "Data Management Using MySQL" },
        { skill: "Javascript JQuery AJAX" },
        { skill: "Knowledge Of Bigbluebutton And Customization (Should Added Extra Privilege)." },
      ],
      minExperience: "",
      requirment: [
        {
          req: "Education: (UG - Any Graduate - Any Specialization) And (PG - Any PG Course - Any Specialization, Post Graduation Not Required)",
        },
        { req: "Industry: Web, Software Development, Design, Mobile App" },
        { req: "Functional Area: Web, Software Development" },
        { req: "Role Category: Senior Drupal Developer" },
        { req: "Minimum Experience : 3 Yrs Onwards" },
      ],
      vacancy: "2",
    },
    {id: 9,
      label: "Core Java Developer",
      images: "assets/images/icons/java.png",
      description:"Deal Candidates Must Be Fully Competent With Key Technical Skills Including:",
      skills: [
        { skill: "Proven Track Record Of Relevant Industry/Technology Experience For At Least 2 Years" },
        { skill: "Good Knowledge Of Core JAVA, Spring, Hibernate, SQL Queries, Struts" },
        { skill: "Knowledge Of Linux And Unix System Is Preferred" },
        {
          skill:
            "Experience With MySQL & Oracle Will Be An Added Advantage",
        },
        { skill: "Understanding Of Software Design Patterns And Object Oriented Design" },
        { skill: "Experience In SOAP, REST, And Third Party API Integrations" },
        { skill: "Exposure To ISO 8583, OFS And Banking Integrations With Be An Added Advantage" },
        { skill: "Ability To Work On Multiple Talks And Priorities Efficiently" },
        { skill: "Experience With Agile Development" },
        { skill: "Strong Interpersonal Skills, Team Player, Gel With Team And Contributor" },
        { skill: "Good Written And Verbal Communication In English Language" },
      ],
      minExperience: "",
      requirment: [],
      vacancy: "2",
    },
    {id: 10,
      label: "Hybrid Mobile App Developers",
      images: "assets/images/icons/hybrid.png",
      description:"Deal Candidates Must Be Fully Competent With Key Technical Skills Including:",
      skills: [
        { skill: "Should Have Expertise In Hybrid Mobile App Development Using Cordova, Ionic Framework 4/5, React Native,Redux Framework, Angular, JavaScript, Typescript, ES6 And JQuery" },
        { skill: "Development Experience With Hybrid Technologies Such As Ionic, Apache Cordova." },
        { skill: "Familiarity With Common Development Tools Such As XCode, Android Software Development Kit (SDK), Git, Windows/Ubuntu/OS X" },
        {
          skill:
            "Should Have Knowledge Of Firebase, Google Map Integration, Bank ,Payment Gateway Integration.",
        },
        { skill: "Should Have Knowledge Of Release Applications To Google Play Stores." },
        { skill: "Have Good Understanding Of Node.JS Is Additional." },
        { skill: "Web Services With SOA Methodology." },
        { skill: "Minimum Experience : 2 Yrs Onwards" },
      ],
      minExperience: "",
      requirment: [],
      vacancy: "2",
    },
    {id: 11,
      label: "Ios Developers",
      images: "assets/images/icons/ios.png",
      description:"Deal Candidates Must Be Fully Competent With Key Technical Skills Including:",
      skills: [
        { skill: "Enterprise Mobility Applications Development Experience Using IOS Platforms." },
        { skill: "Knowledge Of The IPhone App Store / Google Play, App Build Submission And Coding Standards." },
        { skill: "Extensive Experience On Native App Development Using XCode, Objective-C" },
        {
          skill:
            "Expert Level Knowledge On IOS Fundamentals And Application Architecture.",
        },
        { skill: "Object Oriented Programming Concepts." },
        { skill: "Complete Understanding Of The IOS App Ecosystem." },
        { skill: "Database: Oracle, SQL Server, MySQL, DB2, SQL, PL/SQL, JDBC." },
        { skill: "Web Services With SOA Methodology." },
        { skill: "Hands On Experience On Hybrid Mobile Platforms Like PhoneGap." },
        { skill: "Web Applications Development Experience Using HTML5, CSS3, JQuery Mobile, JSON, XML, AJAX Standards, Java Scripts." },
      ],
      minExperience: "",
      requirment: [],
      vacancy: "2",
    },
    {id: 12,
      label: "Android Developers",
      images: "assets/images/icons/android.png",
      description:"Deal Candidates Must Be Fully Competent With Key Technical Skills Including:",
      skills: [
        { skill: "Enterprise Mobility Applications Development Experience Using Android Platforms." },
        { skill: "Experience In Latest Android SDK, J2ME, Eclipse IDE (For Android)." },
        { skill: "Knowledge Of The IPhone App Store / Google Play, App Build Submission And Coding Standards." },
        {
          skill:
            "Extensive Experience On Native App Development Using XCode, Objective-C, Android SDK",
        },
        { skill: "Expert Level Knowledge On Android Fundamentals And Application Architecture." },
        { skill: "Object Oriented Programming Concepts." },
        { skill: "Complete Understanding Of The Android App Ecosystem." },
        { skill: "Database: Oracle, SQL Server, MySQL, DB2, SQL, PL/SQL, JDBC." },
        { skill: "Web Services With SOA Methodology." },
        { skill: "Hands On Experience On Hybrid Mobile Platforms Like PhoneGap." },
        { skill: "Web Applications Development Experience Using HTML5, CSS3, JQuery Mobile, JSON, XML, AJAX Standards, Java Scripts." },
      ],
      minExperience: "",
      requirment: [],
      vacancy: "2",
    },
    {id: 13,
      label: "Online Bidder",
      images: "assets/images/icons/bidder.png",
      description:"Deal Candidates Must Be Fully Competent With Key Technical Skills Including:",
      skills: [
        { skill: "Good Communication & Marketing Skill" },
        { skill: "Knowledge About Website Design, Development And Graphics Work" },
        { skill: "Good In Gathering Requirements From Client" },
        {
          skill:
            "One Point Contact Between Client & Project Manger",
        },
        { skill: "Well Conversant In English - With Good Writing And Understanding Skill - To Work In Overseas Projects." },
        { skill: "Education: (UG - Any Graduate - Any Specialization) And (PG - Any PG Course - Any Specialization, Post Graduation Not Required)" },
        { skill: "Industry: Web Development, Design" },
        { skill: "Functional Area: Web Development" },
        { skill: "Role Category: Online Bidder" },
        { skill: "Minimum Experience : 1 Yr" },
      ],
      minExperience: "",
      requirment: [],
      vacancy: "2",
    },
    {id: 14,
      label: "Business Development Executive",
      images: "assets/images/icons/bdm.png",
      description:"Deal Candidates Must Be Fully Competent With Key Technical Skills Including:",
      skills: [
        { skill: "Professional Need To Acquire Web Development Project From Offline." },
        { skill: "Ability To Interact Directly With Local Clients." },
        { skill: "Cold Calling To Present Our Services And Gain Information About The Target Company." },
        {
          skill:
            "Populating Leads For Mobile Applications.",
        },
        { skill: "Determining A Prospects Level Of Interest And Qualifying The Lead Based On A Set Of Predetermined Requirements." },
        { skill: "Should Have Good Written And Oral Communications Skills In English" },
        { skill: "Education: (UG - Any Graduate - Any Specialization) And (PG - Any PG Course - Any Specialization, Post Graduation Not Required)" },
        { skill: "Industry: Web Development, Design" },
        { skill: "Functional Area: Web Development" },
        { skill: "Role Category: Business Development Executive" },
        { skill: "Minimum Experience : 1 Yr" },
      ],
      minExperience: "",
      requirment: [],
      vacancy: "2",
    },
    {id: 15,
      label: "Hr Executive",
      images: "assets/images/icons/hr.png",
      description:"Deal Candidates Must Be Fully Competent With Key Technical Skills Including:",
      skills: [
        { skill: "Assist With Day To Day Operations Of The HR Functions And Duties Compile And Update Employee Records (Hard And Soft Copies) Process Documentation And Prepare Reports Relating To Personnel Activities (Staffing, Recruitment, Training, Grievances, Performance Evaluations Etc)" },
        { skill: "Deal With Employee Requests Regarding Human Resources Issues, Rules, And Regulations" },
        { skill: "Assist In Payroll Preparation By Providing Relevant Data (Absences, Bonus, Leaves, Etc)" },
        {
          skill:
            "Education: BBA, MBA Preferred (Not Mandatory)",
        },
        { skill: "Industry: Web Development" },
        { skill: "Functional Area: HR Functions" },
        { skill: "Role Category: Human Resource" },
        { skill: "Minimum Experience : 0-1 Year" },
      ],
      minExperience: "",
      requirment: [],
      vacancy: "2",
    },
    {id: 16,
      label: "Seo Executive",
      images: "assets/images/icons/seo.png",
      description:"Deal Candidates Must Be Fully Competent With Key Technical Skills Including:",
      skills: [
        { skill: "Good Communication & Marketing Skill" },
        { skill: "Experience With Website Analysis Using A Variety Of Analytics Tools Including Google Analytics As Well As Internal Reporting Tool Knowledge On SEO, SNO, SMM, B2B & B2C, PPC Campaigns, Google Analytics, Affiliate Marketing" },
        { skill: "Optimize Content For The Website And Social Networking Channels Such As Facebook, Twitter Etc." },
        {
          skill:
            " Top Keywords Ranking By Category",
        },
        { skill: "Research And Analyze Competitor Advertising Links" },
        { skill: "Back Link Strategy And Implementation" },
        { skill: "Directory Submissions And Revisions" },
        { skill: "Internal Link Optimization" },
        { skill: "SEO Technical Analysis And Evaluation" },
        { skill: "Key Phrase Research" },
        { skill: "META Optimization" },
        { skill: "Stay Up To Date On The Latest Industry Developments" },
        { skill: "Education: (UG - Any Graduate - Any Specialization) And (PG - Any PG Course - Any Specialization, Post Graduation Not Required)" },
        { skill: "Industry: Web, Software, App Development, Design" },
        { skill: "Functional Area: IT Software - ECommerce, Internet Technologies" },
        { skill: "Role Category: SEO Executive" },
        { skill: "Minimum Experience : 2 Yrs" },
      ],
      minExperience: "",
      requirment: [],
      vacancy: "2",
    },
    {id: 17,
      label: "Python Developer",
      images: "assets/images/icons/python.png",
      description:"Deal Candidates Must Be Fully Competent With Key Technical Skills Including:",
      skills: [
        { skill: "Expert In Python, Must Know Atleast One Python Web Framework Such As Django, Flask, Etc." },
        { skill: "Familiarity With Some ORM (Object Relational Mapper) Libraries." },
        { skill: "Python Core, Multitasking, Multithreading, GIL, Profiling With CPython In Details" },
        {
          skill:
            "Expert In Relational Databases (MySQL/Postgresql)",
        },
        { skill: "Understanding Of The Threading Limitations Of Python, And Multi-Process Architecture." },
        { skill: "Django Middleware, Mixin." },
        { skill: "Work Experience On RabbitMQ, Redis, Celery And Any Of Nosql (MongoDB/CouchDB)" },
        { skill: "Education: (UG - Any Graduate - Any Specialization) And (PG - Any PG Course - Any Specialization, Post Graduation Not Required)" },
        { skill: "Functional Area: Web, Software Development" },
        { skill: "Minimum Experience : 1 Yr" },
      ],
      minExperience: "",
      requirment: [],
      vacancy: "2",
    },
  ];




  export default data;
  